spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: kafka-poison-pill
      # ErrorHandlingDeserializer wraps StringDeserializer for keys and JsonDeserializer for values.
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        # Set JsonDeserializer specific properties
        spring.json.trusted.packages: '*'
        # Specify actual deserializer for successful cases
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    